# Generated by Django 3.1.4 on 2020-12-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('campeonato_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('epoca', models.CharField(max_length=20)),
                ('datainicio', models.DateField(blank=True, null=True)),
                ('datafim', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campeonato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('modalidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('equipa', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='equipas.equipa')),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
    ]
