# Generated by Django 3.1.4 on 2020-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('jogador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, max_length=5, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jogador',
                'managed': False,
            },
        ),
    ]
