# Generated by Django 3.1.4 on 2020-12-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('equipa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'equipa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('faixa_etaria_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faixa_etaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('modalidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('equipa', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='equipas.equipa')),
            ],
            options={
                'db_table': 'plantel',
                'managed': False,
            },
        ),
    ]
