# Generated by Django 3.1.4 on 2020-12-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('equipa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'equipa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tempo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('faixa_etaria_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faixa_etaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('jogador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, max_length=5, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jogador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('jogo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tempojogo', models.CharField(blank=True, max_length=20, null=True)),
                ('campo', models.CharField(blank=True, max_length=50, null=True)),
                ('espetadores', models.IntegerField(blank=True, null=True)),
                ('diajogo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('modalidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParteJogo',
            fields=[
                ('parte_jogo_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parte_jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('tipo_evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('equipa', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jogos.equipa')),
            ],
            options={
                'db_table': 'plantel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jogos.jogo')),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'resultado',
                'managed': False,
            },
        ),
    ]
