# Generated by Django 3.1.4 on 2020-12-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaixaEtaria',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='equipa',
        ),
        migrations.DeleteModel(
            name='Equipa',
        ),
        migrations.DeleteModel(
            name='Plantel',
        ),
    ]
